# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated from the TL schema at layer 228. Do not edit by hand;
# run codegen/gen_tl.py instead.
"""The abstract TL types, as aliases for type checkers.

Nothing here exists at runtime; see the note in any of the modules.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from . import account as account
    from . import aicompose as aicompose
    from . import auth as auth
    from . import bots as bots
    from . import channels as channels
    from . import chatlists as chatlists
    from . import communities as communities
    from . import contacts as contacts
    from . import fragment as fragment
    from . import help as help
    from . import messages as messages
    from . import payments as payments
    from . import phone as phone
    from . import photos as photos
    from . import premium as premium
    from . import smsjobs as smsjobs
    from . import stats as stats
    from . import stickers as stickers
    from . import storage as storage
    from . import stories as stories
    from . import updates as updates
    from . import upload as upload
    from . import users as users
    from ._root import AccessPointRule as AccessPointRule
    from ._root import AccountDaysTTL as AccountDaysTTL
    from ._root import AiComposeTone as AiComposeTone
    from ._root import AiComposeToneExample as AiComposeToneExample
    from ._root import AttachMenuBot as AttachMenuBot
    from ._root import AttachMenuBotIcon as AttachMenuBotIcon
    from ._root import AttachMenuBotIconColor as AttachMenuBotIconColor
    from ._root import AttachMenuBots as AttachMenuBots
    from ._root import AttachMenuBotsBot as AttachMenuBotsBot
    from ._root import AttachMenuPeerType as AttachMenuPeerType
    from ._root import AuctionBidLevel as AuctionBidLevel
    from ._root import Authorization as Authorization
    from ._root import AutoDownloadSettings as AutoDownloadSettings
    from ._root import AutoSaveException as AutoSaveException
    from ._root import AutoSaveSettings as AutoSaveSettings
    from ._root import AvailableEffect as AvailableEffect
    from ._root import AvailableReaction as AvailableReaction
    from ._root import BadMsgNotification as BadMsgNotification
    from ._root import BankCardOpenUrl as BankCardOpenUrl
    from ._root import BaseTheme as BaseTheme
    from ._root import BindAuthKeyInner as BindAuthKeyInner
    from ._root import Birthday as Birthday
    from ._root import Boost as Boost
    from ._root import BotApp as BotApp
    from ._root import BotAppSettings as BotAppSettings
    from ._root import BotBusinessConnection as BotBusinessConnection
    from ._root import BotCommand as BotCommand
    from ._root import BotCommandScope as BotCommandScope
    from ._root import BotInfo as BotInfo
    from ._root import BotInlineMessage as BotInlineMessage
    from ._root import BotInlineResult as BotInlineResult
    from ._root import BotMenuButton as BotMenuButton
    from ._root import BotPreviewMedia as BotPreviewMedia
    from ._root import BotVerification as BotVerification
    from ._root import BotVerifierSettings as BotVerifierSettings
    from ._root import BusinessAwayMessage as BusinessAwayMessage
    from ._root import BusinessAwayMessageSchedule as BusinessAwayMessageSchedule
    from ._root import BusinessBotRecipients as BusinessBotRecipients
    from ._root import BusinessBotRights as BusinessBotRights
    from ._root import BusinessChatLink as BusinessChatLink
    from ._root import BusinessGreetingMessage as BusinessGreetingMessage
    from ._root import BusinessIntro as BusinessIntro
    from ._root import BusinessLocation as BusinessLocation
    from ._root import BusinessRecipients as BusinessRecipients
    from ._root import BusinessWeeklyOpen as BusinessWeeklyOpen
    from ._root import BusinessWorkHours as BusinessWorkHours
    from ._root import CdnConfig as CdnConfig
    from ._root import CdnPublicKey as CdnPublicKey
    from ._root import ChannelAdminLogEvent as ChannelAdminLogEvent
    from ._root import ChannelAdminLogEventAction as ChannelAdminLogEventAction
    from ._root import ChannelAdminLogEventsFilter as ChannelAdminLogEventsFilter
    from ._root import ChannelLocation as ChannelLocation
    from ._root import ChannelMessagesFilter as ChannelMessagesFilter
    from ._root import ChannelParticipant as ChannelParticipant
    from ._root import ChannelParticipantsFilter as ChannelParticipantsFilter
    from ._root import Chat as Chat
    from ._root import ChatAdminRights as ChatAdminRights
    from ._root import ChatAdminWithInvites as ChatAdminWithInvites
    from ._root import ChatBannedRights as ChatBannedRights
    from ._root import ChatFull as ChatFull
    from ._root import ChatInvite as ChatInvite
    from ._root import ChatInviteImporter as ChatInviteImporter
    from ._root import ChatOnlines as ChatOnlines
    from ._root import ChatParticipant as ChatParticipant
    from ._root import ChatParticipants as ChatParticipants
    from ._root import ChatPhoto as ChatPhoto
    from ._root import ChatReactions as ChatReactions
    from ._root import ChatTheme as ChatTheme
    from ._root import ClientDHInnerData as ClientDHInnerData
    from ._root import CodeSettings as CodeSettings
    from ._root import CommunityPeer as CommunityPeer
    from ._root import CommunityPeerRequest as CommunityPeerRequest
    from ._root import Config as Config
    from ._root import ConnectedBot as ConnectedBot
    from ._root import ConnectedBotStarRef as ConnectedBotStarRef
    from ._root import Contact as Contact
    from ._root import ContactBirthday as ContactBirthday
    from ._root import ContactStatus as ContactStatus
    from ._root import DataJSON as DataJSON
    from ._root import DcOption as DcOption
    from ._root import DefaultHistoryTTL as DefaultHistoryTTL
    from ._root import DestroyAuthKeyRes as DestroyAuthKeyRes
    from ._root import DestroySessionRes as DestroySessionRes
    from ._root import Dialog as Dialog
    from ._root import DialogFilter as DialogFilter
    from ._root import DialogFilterSuggested as DialogFilterSuggested
    from ._root import DialogPeer as DialogPeer
    from ._root import DisallowedGiftsSettings as DisallowedGiftsSettings
    from ._root import Document as Document
    from ._root import DocumentAttribute as DocumentAttribute
    from ._root import DraftMessage as DraftMessage
    from ._root import EmailVerification as EmailVerification
    from ._root import EmailVerifyPurpose as EmailVerifyPurpose
    from ._root import EmojiGroup as EmojiGroup
    from ._root import EmojiKeyword as EmojiKeyword
    from ._root import EmojiKeywordsDifference as EmojiKeywordsDifference
    from ._root import EmojiLanguage as EmojiLanguage
    from ._root import EmojiList as EmojiList
    from ._root import EmojiStatus as EmojiStatus
    from ._root import EmojiURL as EmojiURL
    from ._root import EncryptedChat as EncryptedChat
    from ._root import EncryptedFile as EncryptedFile
    from ._root import EncryptedMessage as EncryptedMessage
    from ._root import EphemeralMessage as EphemeralMessage
    from ._root import Error as Error
    from ._root import ExportedChatInvite as ExportedChatInvite
    from ._root import ExportedChatlistInvite as ExportedChatlistInvite
    from ._root import ExportedContactToken as ExportedContactToken
    from ._root import ExportedMessageLink as ExportedMessageLink
    from ._root import ExportedStoryLink as ExportedStoryLink
    from ._root import FactCheck as FactCheck
    from ._root import FileHash as FileHash
    from ._root import Folder as Folder
    from ._root import FolderPeer as FolderPeer
    from ._root import ForumTopic as ForumTopic
    from ._root import FoundStory as FoundStory
    from ._root import FutureSalt as FutureSalt
    from ._root import FutureSalts as FutureSalts
    from ._root import Game as Game
    from ._root import GeoPoint as GeoPoint
    from ._root import GeoPointAddress as GeoPointAddress
    from ._root import GlobalPrivacySettings as GlobalPrivacySettings
    from ._root import GroupCall as GroupCall
    from ._root import GroupCallDonor as GroupCallDonor
    from ._root import GroupCallMessage as GroupCallMessage
    from ._root import GroupCallParticipant as GroupCallParticipant
    from ._root import GroupCallParticipantVideo as GroupCallParticipantVideo
    from ._root import GroupCallParticipantVideoSourceGroup as GroupCallParticipantVideoSourceGroup
    from ._root import GroupCallStreamChannel as GroupCallStreamChannel
    from ._root import HighScore as HighScore
    from ._root import HttpWait as HttpWait
    from ._root import ImportedContact as ImportedContact
    from ._root import InlineBotSwitchPM as InlineBotSwitchPM
    from ._root import InlineBotWebView as InlineBotWebView
    from ._root import InlineQueryPeerType as InlineQueryPeerType
    from ._root import InputAiComposeTone as InputAiComposeTone
    from ._root import InputAppEvent as InputAppEvent
    from ._root import InputBotApp as InputBotApp
    from ._root import InputBotInlineMessage as InputBotInlineMessage
    from ._root import InputBotInlineMessageID as InputBotInlineMessageID
    from ._root import InputBotInlineResult as InputBotInlineResult
    from ._root import InputBusinessAwayMessage as InputBusinessAwayMessage
    from ._root import InputBusinessBotRecipients as InputBusinessBotRecipients
    from ._root import InputBusinessChatLink as InputBusinessChatLink
    from ._root import InputBusinessGreetingMessage as InputBusinessGreetingMessage
    from ._root import InputBusinessIntro as InputBusinessIntro
    from ._root import InputBusinessRecipients as InputBusinessRecipients
    from ._root import InputChannel as InputChannel
    from ._root import InputChatPhoto as InputChatPhoto
    from ._root import InputChatTheme as InputChatTheme
    from ._root import InputChatlist as InputChatlist
    from ._root import InputCheckPasswordSRP as InputCheckPasswordSRP
    from ._root import InputClientProxy as InputClientProxy
    from ._root import InputCollectible as InputCollectible
    from ._root import InputContact as InputContact
    from ._root import InputDialogPeer as InputDialogPeer
    from ._root import InputDocument as InputDocument
    from ._root import InputEncryptedChat as InputEncryptedChat
    from ._root import InputEncryptedFile as InputEncryptedFile
    from ._root import InputFile as InputFile
    from ._root import InputFileLocation as InputFileLocation
    from ._root import InputFolderPeer as InputFolderPeer
    from ._root import InputGame as InputGame
    from ._root import InputGeoPoint as InputGeoPoint
    from ._root import InputGroupCall as InputGroupCall
    from ._root import InputInvoice as InputInvoice
    from ._root import InputMedia as InputMedia
    from ._root import InputMessage as InputMessage
    from ._root import InputMessageReadMetric as InputMessageReadMetric
    from ._root import InputNotifyPeer as InputNotifyPeer
    from ._root import InputPasskeyCredential as InputPasskeyCredential
    from ._root import InputPasskeyResponse as InputPasskeyResponse
    from ._root import InputPaymentCredentials as InputPaymentCredentials
    from ._root import InputPeer as InputPeer
    from ._root import InputPeerNotifySettings as InputPeerNotifySettings
    from ._root import InputPhoneCall as InputPhoneCall
    from ._root import InputPhoto as InputPhoto
    from ._root import InputPrivacyKey as InputPrivacyKey
    from ._root import InputPrivacyRule as InputPrivacyRule
    from ._root import InputQuickReplyShortcut as InputQuickReplyShortcut
    from ._root import InputReplyTo as InputReplyTo
    from ._root import InputRichFile as InputRichFile
    from ._root import InputRichMessage as InputRichMessage
    from ._root import InputSavedStarGift as InputSavedStarGift
    from ._root import InputSecureFile as InputSecureFile
    from ._root import InputSecureValue as InputSecureValue
    from ._root import InputSingleMedia as InputSingleMedia
    from ._root import InputStarGiftAuction as InputStarGiftAuction
    from ._root import InputStarsTransaction as InputStarsTransaction
    from ._root import InputStickerSet as InputStickerSet
    from ._root import InputStickerSetItem as InputStickerSetItem
    from ._root import InputStickeredMedia as InputStickeredMedia
    from ._root import InputStorePaymentPurpose as InputStorePaymentPurpose
    from ._root import InputTheme as InputTheme
    from ._root import InputThemeSettings as InputThemeSettings
    from ._root import InputUser as InputUser
    from ._root import InputWallPaper as InputWallPaper
    from ._root import InputWebDocument as InputWebDocument
    from ._root import InputWebFileLocation as InputWebFileLocation
    from ._root import Invoice as Invoice
    from ._root import IpPort as IpPort
    from ._root import JSONObjectValue as JSONObjectValue
    from ._root import JSONValue as JSONValue
    from ._root import JoinChatBotResult as JoinChatBotResult
    from ._root import KeyboardButton as KeyboardButton
    from ._root import KeyboardButtonRow as KeyboardButtonRow
    from ._root import KeyboardButtonStyle as KeyboardButtonStyle
    from ._root import LabeledPrice as LabeledPrice
    from ._root import LangPackDifference as LangPackDifference
    from ._root import LangPackLanguage as LangPackLanguage
    from ._root import LangPackString as LangPackString
    from ._root import MaskCoords as MaskCoords
    from ._root import MediaArea as MediaArea
    from ._root import MediaAreaCoordinates as MediaAreaCoordinates
    from ._root import Message as Message
    from ._root import MessageAction as MessageAction
    from ._root import MessageEntity as MessageEntity
    from ._root import MessageExtendedMedia as MessageExtendedMedia
    from ._root import MessageFwdHeader as MessageFwdHeader
    from ._root import MessageMedia as MessageMedia
    from ._root import MessagePeerReaction as MessagePeerReaction
    from ._root import MessagePeerVote as MessagePeerVote
    from ._root import MessageRange as MessageRange
    from ._root import MessageReactions as MessageReactions
    from ._root import MessageReactor as MessageReactor
    from ._root import MessageReplies as MessageReplies
    from ._root import MessageReplyHeader as MessageReplyHeader
    from ._root import MessageReportOption as MessageReportOption
    from ._root import MessageViews as MessageViews
    from ._root import MessagesFilter as MessagesFilter
    from ._root import MissingInvitee as MissingInvitee
    from ._root import MsgDetailedInfo as MsgDetailedInfo
    from ._root import MsgResendReq as MsgResendReq
    from ._root import MsgsAck as MsgsAck
    from ._root import MsgsAllInfo as MsgsAllInfo
    from ._root import MsgsStateInfo as MsgsStateInfo
    from ._root import MsgsStateReq as MsgsStateReq
    from ._root import MyBoost as MyBoost
    from ._root import NearestDc as NearestDc
    from ._root import NewSession as NewSession
    from ._root import NotificationSound as NotificationSound
    from ._root import NotifyPeer as NotifyPeer
    from ._root import Null as Null
    from ._root import OutboxReadDate as OutboxReadDate
    from ._root import PQInnerData as PQInnerData
    from ._root import Page as Page
    from ._root import PageBlock as PageBlock
    from ._root import PageCaption as PageCaption
    from ._root import PageListItem as PageListItem
    from ._root import PageListOrderedItem as PageListOrderedItem
    from ._root import PageRelatedArticle as PageRelatedArticle
    from ._root import PageTableCell as PageTableCell
    from ._root import PageTableRow as PageTableRow
    from ._root import PaidReactionPrivacy as PaidReactionPrivacy
    from ._root import Passkey as Passkey
    from ._root import PasswordKdfAlgo as PasswordKdfAlgo
    from ._root import PaymentCharge as PaymentCharge
    from ._root import PaymentFormMethod as PaymentFormMethod
    from ._root import PaymentRequestedInfo as PaymentRequestedInfo
    from ._root import PaymentSavedCredentials as PaymentSavedCredentials
    from ._root import Peer as Peer
    from ._root import PeerBlocked as PeerBlocked
    from ._root import PeerColor as PeerColor
    from ._root import PeerLocated as PeerLocated
    from ._root import PeerNotifySettings as PeerNotifySettings
    from ._root import PeerSettings as PeerSettings
    from ._root import PeerStories as PeerStories
    from ._root import PendingSuggestion as PendingSuggestion
    from ._root import PhoneCall as PhoneCall
    from ._root import PhoneCallDiscardReason as PhoneCallDiscardReason
    from ._root import PhoneCallProtocol as PhoneCallProtocol
    from ._root import PhoneConnection as PhoneConnection
    from ._root import Photo as Photo
    from ._root import PhotoSize as PhotoSize
    from ._root import Poll as Poll
    from ._root import PollAnswer as PollAnswer
    from ._root import PollAnswerVoters as PollAnswerVoters
    from ._root import PollResults as PollResults
    from ._root import Pong as Pong
    from ._root import PopularContact as PopularContact
    from ._root import PostAddress as PostAddress
    from ._root import PostInteractionCounters as PostInteractionCounters
    from ._root import PremiumGiftCodeOption as PremiumGiftCodeOption
    from ._root import PremiumSubscriptionOption as PremiumSubscriptionOption
    from ._root import PrepaidGiveaway as PrepaidGiveaway
    from ._root import PrivacyKey as PrivacyKey
    from ._root import PrivacyRule as PrivacyRule
    from ._root import ProfileTab as ProfileTab
    from ._root import PublicForward as PublicForward
    from ._root import QuickReply as QuickReply
    from ._root import Reaction as Reaction
    from ._root import ReactionCount as ReactionCount
    from ._root import ReactionNotificationsFrom as ReactionNotificationsFrom
    from ._root import ReactionsNotifySettings as ReactionsNotifySettings
    from ._root import ReadParticipantDate as ReadParticipantDate
    from ._root import ReceivedNotifyMessage as ReceivedNotifyMessage
    from ._root import RecentMeUrl as RecentMeUrl
    from ._root import RecentStory as RecentStory
    from ._root import ReplyMarkup as ReplyMarkup
    from ._root import ReportReason as ReportReason
    from ._root import ReportResult as ReportResult
    from ._root import RequestPeerType as RequestPeerType
    from ._root import RequestedPeer as RequestedPeer
    from ._root import RequirementToContact as RequirementToContact
    from ._root import ResPQ as ResPQ
    from ._root import RestrictionReason as RestrictionReason
    from ._root import RichMessage as RichMessage
    from ._root import RichText as RichText
    from ._root import RpcDropAnswer as RpcDropAnswer
    from ._root import RpcError as RpcError
    from ._root import SavedContact as SavedContact
    from ._root import SavedDialog as SavedDialog
    from ._root import SavedReactionTag as SavedReactionTag
    from ._root import SavedStarGift as SavedStarGift
    from ._root import SearchPostsFlood as SearchPostsFlood
    from ._root import SearchResultsCalendarPeriod as SearchResultsCalendarPeriod
    from ._root import SearchResultsPosition as SearchResultsPosition
    from ._root import SecureCredentialsEncrypted as SecureCredentialsEncrypted
    from ._root import SecureData as SecureData
    from ._root import SecureFile as SecureFile
    from ._root import SecurePasswordKdfAlgo as SecurePasswordKdfAlgo
    from ._root import SecurePlainData as SecurePlainData
    from ._root import SecureRequiredType as SecureRequiredType
    from ._root import SecureSecretSettings as SecureSecretSettings
    from ._root import SecureValue as SecureValue
    from ._root import SecureValueError as SecureValueError
    from ._root import SecureValueHash as SecureValueHash
    from ._root import SecureValueType as SecureValueType
    from ._root import SendAsPeer as SendAsPeer
    from ._root import SendMessageAction as SendMessageAction
    from ._root import ServerDHInnerData as ServerDHInnerData
    from ._root import ServerDHParams as ServerDHParams
    from ._root import SetClientDHParamsAnswer as SetClientDHParamsAnswer
    from ._root import ShippingOption as ShippingOption
    from ._root import SmsJob as SmsJob
    from ._root import SponsoredMessage as SponsoredMessage
    from ._root import SponsoredMessageReportOption as SponsoredMessageReportOption
    from ._root import SponsoredPeer as SponsoredPeer
    from ._root import StarGift as StarGift
    from ._root import StarGiftActiveAuctionState as StarGiftActiveAuctionState
    from ._root import StarGiftAttribute as StarGiftAttribute
    from ._root import StarGiftAttributeCounter as StarGiftAttributeCounter
    from ._root import StarGiftAttributeId as StarGiftAttributeId
    from ._root import StarGiftAttributeRarity as StarGiftAttributeRarity
    from ._root import StarGiftAuctionAcquiredGift as StarGiftAuctionAcquiredGift
    from ._root import StarGiftAuctionRound as StarGiftAuctionRound
    from ._root import StarGiftAuctionState as StarGiftAuctionState
    from ._root import StarGiftAuctionUserState as StarGiftAuctionUserState
    from ._root import StarGiftBackground as StarGiftBackground
    from ._root import StarGiftCollection as StarGiftCollection
    from ._root import StarGiftUpgradePrice as StarGiftUpgradePrice
    from ._root import StarRefProgram as StarRefProgram
    from ._root import StarsAmount as StarsAmount
    from ._root import StarsGiftOption as StarsGiftOption
    from ._root import StarsGiveawayOption as StarsGiveawayOption
    from ._root import StarsGiveawayWinnersOption as StarsGiveawayWinnersOption
    from ._root import StarsRating as StarsRating
    from ._root import StarsRevenueStatus as StarsRevenueStatus
    from ._root import StarsSubscription as StarsSubscription
    from ._root import StarsSubscriptionPricing as StarsSubscriptionPricing
    from ._root import StarsTopupOption as StarsTopupOption
    from ._root import StarsTransaction as StarsTransaction
    from ._root import StarsTransactionPeer as StarsTransactionPeer
    from ._root import StatsAbsValueAndPrev as StatsAbsValueAndPrev
    from ._root import StatsDateRangeDays as StatsDateRangeDays
    from ._root import StatsGraph as StatsGraph
    from ._root import StatsGroupTopAdmin as StatsGroupTopAdmin
    from ._root import StatsGroupTopInviter as StatsGroupTopInviter
    from ._root import StatsGroupTopPoster as StatsGroupTopPoster
    from ._root import StatsPercentValue as StatsPercentValue
    from ._root import StatsURL as StatsURL
    from ._root import StickerKeyword as StickerKeyword
    from ._root import StickerPack as StickerPack
    from ._root import StickerSet as StickerSet
    from ._root import StickerSetCovered as StickerSetCovered
    from ._root import StoriesStealthMode as StoriesStealthMode
    from ._root import StoryAlbum as StoryAlbum
    from ._root import StoryFwdHeader as StoryFwdHeader
    from ._root import StoryItem as StoryItem
    from ._root import StoryReaction as StoryReaction
    from ._root import StoryView as StoryView
    from ._root import StoryViews as StoryViews
    from ._root import SuggestedPost as SuggestedPost
    from ._root import TextWithEntities as TextWithEntities
    from ._root import Theme as Theme
    from ._root import ThemeSettings as ThemeSettings
    from ._root import Timezone as Timezone
    from ._root import TodoCompletion as TodoCompletion
    from ._root import TodoItem as TodoItem
    from ._root import TodoList as TodoList
    from ._root import TopPeer as TopPeer
    from ._root import TopPeerCategory as TopPeerCategory
    from ._root import TopPeerCategoryPeers as TopPeerCategoryPeers
    from ._root import Update as Update
    from ._root import Updates as Updates
    from ._root import UrlAuthResult as UrlAuthResult
    from ._root import User as User
    from ._root import UserFull as UserFull
    from ._root import UserProfilePhoto as UserProfilePhoto
    from ._root import UserStatus as UserStatus
    from ._root import Username as Username
    from ._root import VideoSize as VideoSize
    from ._root import WallPaper as WallPaper
    from ._root import WallPaperSettings as WallPaperSettings
    from ._root import WebAuthorization as WebAuthorization
    from ._root import WebDocument as WebDocument
    from ._root import WebDomainException as WebDomainException
    from ._root import WebPage as WebPage
    from ._root import WebPageAttribute as WebPageAttribute
    from ._root import WebViewMessageSent as WebViewMessageSent
    from ._root import WebViewResult as WebViewResult
